/*
DROP TABLE IF EXISTS LOCAL CASCADE;
DROP TABLE IF EXISTS PESSOA CASCADE;
DROP TABLE IF EXISTS EVENTO CASCADE;
DROP TABLE IF EXISTS PARTICIPA CASCADE;
DROP TABLE IF EXISTS TURMA CASCADE;
DROP TABLE IF EXISTS CARGO CASCADE;
DROP TABLE IF EXISTS EMPRESA_FUNCIONARIO CASCADE;
DROP TABLE IF EXISTS TRABALHA CASCADE;
DROP TABLE IF EXISTS INSUMO CASCADE;
DROP TABLE IF EXISTS EMPRESA_INSUMO CASCADE;
DROP TABLE IF EXISTS VENDA_INSUMO CASCADE;
DROP TABLE IF EXISTS VENDA_INSUMO_EVENTO CASCADE;
DROP TABLE IF EXISTS BRINQUEDO CASCADE;
DROP TABLE IF EXISTS EMPRESA_BRINQUEDO CASCADE;
DROP TABLE IF EXISTS VENDA_BRINQUEDO CASCADE;
DROP TABLE IF EXISTS VENDA_BRINQUEDO_FORMATURA CASCADE;
DROP TABLE IF EXISTS PRESENTE CASCADE;
DROP TABLE IF EXISTS EMPRESA_PRESENTE CASCADE;
DROP TABLE IF EXISTS VENDA_PRESENTE CASCADE;
DROP TABLE IF EXISTS VENDA_PRESENTE_CASAMENTO CASCADE;
*/

CREATE TABLE LOCAL(
    ID          SERIAL,
	CIDADE		CHARACTER VARYING(30) NOT NULL,
	RUA			CHARACTER VARYING(30) NOT NULL,
	NUMERO		INTEGER NOT NULL,
	NOME		CHARACTER VARYING(50) NOT NULL,
	TELEFONE	CHARACTER VARYING(14) NOT NULL,
	TAMANHO		INTEGER,
	PRECO		MONEY NOT NULL,
	
	CONSTRAINT PK_LOCAL PRIMARY KEY(ID),
    CONSTRAINT UN_LOCAL UNIQUE(CIDADE, RUA, NUMERO)
);

CREATE TABLE PESSOA(
	CPF			CHAR(14),
    NOME		CHARACTER VARYING(50) NOT NULL,
	TELEFONE	CHARACTER VARYING(14) NOT NULL,
	CIDADE		CHARACTER VARYING(30),
	RUA			CHARACTER VARYING(30),
	NUMERO		INTEGER,
	EMAIL		CHARACTER VARYING(30),

	CONSTRAINT PK_PESSOA PRIMARY KEY (CPF),
	CONSTRAINT CK_CPF CHECK(CPF SIMILAR TO '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')
);

CREATE TABLE EVENTO (
	ID						SERIAL,
	LOCAL					INTEGER,
	DATA					DATE NOT NULL,
	HORA_INICIO				TIME NOT NULL,
	HORA_FIM				TIME,
	TIPO					CHAR(9) NOT NULL,
	CONTRATANTE				CHAR(14),
	DURACAO					INTEGER, -- NUMERO DE HORAS
	QTD_PARTICIPANTES		INTEGER,
	QTD_FUNCIONARIOS		INTEGER,
	PRECO					MONEY,
	PRECO_COMBINADO_LOCAL	MONEY,
	
	CONSTRAINT PK_EVENTO PRIMARY KEY(ID),
    CONSTRAINT FK_EVENTO_LOCAL FOREIGN KEY (LOCAL) REFERENCES LOCAL (ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_EVENTO_CONTRATANTE FOREIGN KEY (CONTRATANTE) REFERENCES PESSOA (CPF)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT UN_EVENTO UNIQUE(LOCAL, DATA, HORA_INICIO)    
);

CREATE TABLE PARTICIPA(
	PESSOA			CHAR(14),
	EVENTO			INTEGER,
	HORA_ENTRADA	TIME,
	HORA_SAIDA		TIME,
	
	CONSTRAINT PK_PARTICIPA PRIMARY KEY (PESSOA, EVENTO),
	CONSTRAINT FK_PARTICIPA_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA (CPF) 
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_PARTICIPA_EVENTO FOREIGN KEY (EVENTO) REFERENCES EVENTO (ID) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TURMA(
	UNIVERSIDADE	CHARACTER VARYING(40),
	ANO				INTEGER,
	CURSO			CHARACTER VARYING(40),
	REPRESENTANTE	CHAR(14) NOT NULL,
	FORMATURA		INTEGER,
	
	CONSTRAINT PK_TURMA PRIMARY KEY (UNIVERSIDADE, ANO, CURSO),
    CONSTRAINT FK_TURMA_REPRESENTANTE FOREIGN KEY (REPRESENTANTE) REFERENCES PESSOA (CPF)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_TURMA_FORMATURA FOREIGN KEY (FORMATURA) REFERENCES EVENTO (ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE CARGO (
	NOME	CHARACTER VARYING(50),
	PRECOH	MONEY,

    CONSTRAINT PK_CARGO PRIMARY KEY (NOME)
);

CREATE TABLE EMPRESA_FUNCIONARIO(
	CNPJ		BIGINT,
	NOME		CHARACTER VARYING(40),
	TELEFONE	CHARACTER VARYING(14) NOT NULL,

	CONSTRAINT PK_EMPRESA_FUNCIONARIO PRIMARY KEY (CNPJ),
    CONSTRAINT CK_EMPRESA_FUNCIONARIO_TELEFONE CHECK (TELEFONE SIMILAR TO '\([0-9]{2}\) [0-9]{4}-[0-9]{4}')	
	-- CONSTRAINT CK_CNPJ CHECK(CNPJ ~ '[0-9]{2}\.[0-9]{3}\.[0-9]{3}\-[0-9]{4}.[0-9]{2}')
);

CREATE TABLE TRABALHA(
	PESSOA					CHAR(14),
	CARGO					CHARACTER VARYING(50) NOT NULL,
	EMPRESA         		BIGINT NOT NULL,
	EVENTO					INTEGER,
	HORAS_TRABALHADAS		INTEGER NOT NULL,
	PRECOH					NUMERIC(10,2),
	SALARIO					NUMERIC(10,2),
	
	CONSTRAINT PK_TRABALHA PRIMARY KEY (PESSOA, EVENTO),
    CONSTRAINT FK_TRABALHA_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(CPF)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_TRABALHA_CARGO FOREIGN KEY (CARGO) REFERENCES CARGO(NOME)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_TRABALHA_EMPRESA FOREIGN KEY (EMPRESA) REFERENCES EMPRESA_FUNCIONARIO(CNPJ)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_TRABALHA_EVENTO FOREIGN KEY (EVENTO) REFERENCES EVENTO(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INSUMO (
	NOME        CHARACTER VARYING(50),
	TIPO        CHARACTER(6), 
	RESTRICAO   CHARACTER(11), 
	PESO        REAL,
	VOLUME      REAL,
	ATIVO       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_INSUMO PRIMARY KEY (NOME),
	CONSTRAINT CK_INSUMO_TIPO CHECK (UPPER(TIPO) IN ('COMIDA', 'BEBIDA')),
	CONSTRAINT CK_INSUMO_RESTRICAO CHECK (UPPER(TIPO) IN ('VEGETARIANA', 'VEGANA', 'CARNIVORA'))		
);

CREATE TABLE EMPRESA_INSUMO (
	CNPJ        BIGINT,
	NOME        CHARACTER VARYING(50), 
	TELEFONE    CHARACTER(14),
	ATIVA       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_EMPRESA_INSUMO PRIMARY KEY (CNPJ),
	CONSTRAINT CK_EMPRESA_INSUMO_TELEFONE CHECK (TELEFONE SIMILAR TO '\([0-9]{2}\) [0-9]{4}-[0-9]{4}')	
);

CREATE TABLE VENDA_INSUMO (
	EMPRESA BIGINT,
	INSUMO  CHARACTER VARYING(50),
	PRECO   MONEY,
	ATIVA   BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_VENDA_INSUMO PRIMARY KEY (EMPRESA, INSUMO),
	CONSTRAINT FK_VENDA_INSUMO_EMPRESA 
		FOREIGN KEY (EMPRESA) REFERENCES EMPRESA_INSUMO(CNPJ) 
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_VENDA_INSUMO_INSUMO 
		FOREIGN KEY (INSUMO) REFERENCES INSUMO(NOME) 
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENDA_INSUMO_EVENTO (
	EMPRESA         BIGINT,
	INSUMO          CHARACTER VARYING(50),
	EVENTO          INTEGER, 
	PRECO_COMBINADO MONEY,
	QTD             SMALLINT,

	CONSTRAINT PK_VENDA_INSUMO_EVENTO PRIMARY KEY (EMPRESA, INSUMO, EVENTO),
	CONSTRAINT FK_VENDA_INSUMO_EVENTO_EMPRESA_INSUMO 
		FOREIGN KEY (EMPRESA, INSUMO) REFERENCES VENDA_INSUMO(EMPRESA, INSUMO)
		ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_VENDA_INSUMO_EVENTO_EVENTO  
        FOREIGN KEY (EVENTO) REFERENCES EVENTO(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_VENDA_INSUMO_EVENTO_QTD CHECK (QTD > 0)
);

CREATE TABLE BRINQUEDO (
	NOME        CHARACTER VARYING(50),
	VALOR       MONEY, 
	AREA		REAL, 
	ATIVO       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_BRINQUEDO PRIMARY KEY (NOME)		
);

CREATE TABLE EMPRESA_BRINQUEDO (
	CNPJ        BIGINT,
	NOME        CHARACTER VARYING(50), 
	TELEFONE    CHARACTER(14),
	ATIVA       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_EMPRESA_BRINQUEDO PRIMARY KEY (CNPJ),
	CONSTRAINT CK_EMPRESA_BRINQUEDO_TELEFONE CHECK (TELEFONE SIMILAR TO '\([0-9]{2}\) [0-9]{4}-[0-9]{4}')
);

CREATE TABLE VENDA_BRINQUEDO (
	EMPRESA 	BIGINT,
	BRINQUEDO 	CHARACTER VARYING(50),
	PRECO   	MONEY,
	ATIVA   	BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_VENDA_BRINQUEDO PRIMARY KEY (EMPRESA, BRINQUEDO),
	CONSTRAINT FK_VENDA_BRINQUEDO_EMPRESA 
		FOREIGN KEY (EMPRESA) REFERENCES EMPRESA_BRINQUEDO(CNPJ) 
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_VENDA_BRINQUEDO_BRINQUEDO 
		FOREIGN KEY (BRINQUEDO) REFERENCES BRINQUEDO(NOME) 
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENDA_BRINQUEDO_FORMATURA (
	EMPRESA         BIGINT,
	BRINQUEDO       CHARACTER VARYING(50),
	FORMATURA       INTEGER,
	PRECO_COMBINADO MONEY,
	QTD             SMALLINT,

	CONSTRAINT PK_VENDA_BRINQUEDO_FORMATURA PRIMARY KEY (EMPRESA, BRINQUEDO, FORMATURA),
	CONSTRAINT FK_VENDA_BRINQUEDO_FORMATURA_EMPRESA_BRINQUEDO 
		FOREIGN KEY (EMPRESA, BRINQUEDO) REFERENCES VENDA_BRINQUEDO(EMPRESA, BRINQUEDO)
		ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_VENDA_BRINQUEDO_FORMATURA_FORMATURA  
        FOREIGN KEY (FORMATURA) REFERENCES EVENTO(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_VENDA_BRINQUEDO_FORMATURA_QTD CHECK (QTD > 0)
);

CREATE TABLE PRESENTE (
	NOME        CHARACTER VARYING(50),
	VALOR       MONEY, 
	ATIVO       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_PRESENTE PRIMARY KEY (NOME)		
);

CREATE TABLE EMPRESA_PRESENTE (
	CNPJ        BIGINT,
	NOME        CHARACTER VARYING(50), 
	TELEFONE    CHARACTER(14),
	ATIVA       BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_EMPRESA_PRESENTE PRIMARY KEY (CNPJ),
	CONSTRAINT CK_EMPRESA_PRESENTE_TELEFONE CHECK (TELEFONE SIMILAR TO '\([0-9]{2}\) [0-9]{4}-[0-9]{4}')
);

CREATE TABLE VENDA_PRESENTE (
	EMPRESA 	BIGINT,
	PRESENTE 	CHARACTER VARYING(50),
	PRECO   	MONEY,
	ATIVA   	BOOLEAN DEFAULT TRUE,
	
	CONSTRAINT PK_VENDA_PRESENTE PRIMARY KEY (EMPRESA, PRESENTE),
	CONSTRAINT FK_VENDA_PRESENTE_EMPRESA 
		FOREIGN KEY (EMPRESA) REFERENCES EMPRESA_PRESENTE(CNPJ) 
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_VENDA_PRESENTE_PRESENTE 
		FOREIGN KEY (PRESENTE) REFERENCES PRESENTE(NOME) 
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENDA_PRESENTE_CASAMENTO (
	EMPRESA         BIGINT,
	PRESENTE        CHARACTER VARYING(50),
	CASAMENTO       INTEGER,
	PRECO_COMBINADO MONEY,
	QTD             SMALLINT,

	CONSTRAINT PK_VENDA_PRESENTE_CASAMENTO PRIMARY KEY (EMPRESA, PRESENTE, CASAMENTO),
	CONSTRAINT FK_VENDA_PRESENTE_CASAMENTO_EMPRESA_PRESENTE 
		FOREIGN KEY (EMPRESA, PRESENTE) REFERENCES VENDA_PRESENTE(EMPRESA, PRESENTE)
		ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_VENDA_PRESENTE_CASAMENTO_CASAMENTO  
        FOREIGN KEY (CASAMENTO) REFERENCES EVENTO(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_VENDA_PRESENTE_CASAMENTO_QTD CHECK (QTD > 0)
);