/*
DROP TABLE TRABALHA;
DROP TABLE PARTICIPA;
DROP TABLE CARGO;
DROP TABLE EMPRESA_FUNCIONARIO;
DROP TABLE TURMA;
DROP TABLE PESSOA;
DROP TABLE EVENTO;
DROP TABLE LOCAL;
*/

CREATE TABLE LOCAL(
	CIDADE		VARCHAR(30) not null,
	RUA			VARCHAR(30) not null,
	NUMERO		INTEGER not null,
	NOME		VARCHAR(50) not null,
	TELEFONE	VARCHAR(14) not null,
	TAMANHO		INTEGER,
	PRECO		NUMERIC(10,2) not null,
	
	CONSTRAINT PK_LOCAL PRIMARY KEY(CIDADE, RUA, NUMERO)
);

CREATE TABLE EVENTO (
	ID						INTEGER not null,
	LOCAL					VARCHAR(50) not null,
	DATA					DATE not null,
	HORA_INICIO				TIME not null,
	HORA_FIM				TIME,
	TIPO					CHAR(9) not null,
	CONTRATANTE				VARCHAR(50) not null,
	DURACAO					INTEGER, -- NUMERO DE HORAS
	QTD_PARTICIPANTES		INTEGER,
	QTD_FUNCIONARIOS		INTEGER,
	PRECO					NUMERIC(10,2),
	PRECO_COMBINADO_LOCAL	NUMERIC(10,2),
	
	CONSTRAINT PK_EVENTO PRIMARY KEY(ID),
	CONSTRAINT UN_EVENTO UNIQUE(LOCAL, DATA, HORA_INICIO)
	-- FALTA FK DE LOCAL
);

CREATE TABLE PESSOA(
	NOME		VARCHAR(50) not null,
	CPF			CHAR(14)  PRIMARY KEY,
	TELEFONE	VARCHAR(14) not null,
	CIDADE		VARCHAR(30),
	RUA			VARCHAR(30),
	NUMERO		INTEGER,
	EMAIL		VARCHAR(30),
	
	CONSTRAINT CK_CPF CHECK(CPF ~ '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')
);

CREATE TABLE PARTICIPA(
	PESSOA			CHAR(14) not null,
	EVENTO			INTEGER not null,
	HORA_ENTRADA	TIME,
	HORA_SAIDA		TIME,
	
	CONSTRAINT PK_PARTICIPA PRIMARY KEY (PESSOA, EVENTO),
	CONSTRAINT FK_PARTICIPA_EVENTO FOREIGN KEY(EVENTO) REFERENCES EVENTO(ID) ON DELETE CASCADE
);

CREATE TABLE TURMA(
	UNIVERSIDADE	VARCHAR(40) not null,
	ANO				INTEGER not null,
	CURSO			VARCHAR(40) not null,
	REPRESENTANTE	CHAR(14) NOT NULL REFERENCES PESSOA(CPF),
	FORMATURA		INTEGER REFERENCES EVENTO(ID),
	
	CONSTRAINT PK_TURMA PRIMARY KEY (UNIVERSIDADE, ANO, CURSO)
);

CREATE TABLE CARGO (
	NOME	VARCHAR(50) PRIMARY KEY,
	PRECOH	NUMERIC(10,2)
);

CREATE TABLE EMPRESA_FUNCIONARIO(
	CNPJ		CHAR(18) PRIMARY KEY, --15digitos + 4 : XX.XXX.XXX/YYYY-ZZ
	NOME		VARCHAR(40),
	TELEFONE	VARCHAR(14) not null,
	
	CONSTRAINT CK_CNPJ CHECK(CNPJ ~ '[0-9]{2}\.[0-9]{3}\.[0-9]{3}\-[0-9]{4}.[0-9]{2}')
);

CREATE TABLE TRABALHA(
	PESSOA					CHAR(14) REFERENCES PESSOA(CPF),
	CARGO					VARCHAR(50) REFERENCES CARGO(NOME),
	EMPRESA_FUNCIONARIO		CHAR(19) NOT NULL REFERENCES EMPRESA_FUNCIONARIO(CNPJ),
	EVENTO					INTEGER not null,
	HORAS_TRABALHADAS		INTEGER not null,
	PRECOH					NUMERIC(10,2),
	SALARIO					NUMERIC(10,2),
	
	CONSTRAINT PK_TRABALHA PRIMARY KEY (PESSOA, EVENTO)
);

