-- RELATÓRIO DE PARTICIPANTES E FUNCIONÁRIOS DO EVENTO
(SELECT 
	P.CPF,
	P.NOME, 
	'PARTICIPANTE'  AS CONDICAO
FROM PESSOA P 
INNER JOIN PARTICIPA PA ON P.CPF = PA.PESSOA
WHERE 
	PA.EVENTO = 2)
UNION
(SELECT 
	P.CPF,
	P.NOME, 
	'FUNCIONÁRIO' AS CONDICAO
FROM PESSOA P
INNER JOIN TRABALHA T ON P.CPF = T.PESSOA
WHERE 
	T.EVENTO = 2)

-- FUNCIONÁRIOS DE UMA DETERMINADA FUNÇÃO DO EVENTO
SELECT 
    P.CPF,
    P.NOME,
    E.NOME AS EMPRESA
FROM PESSOA P
INNER JOIN TRABALHA T ON P.CPF = T.PESSOA
INNER JOIN EMPRESA_FUNCIONARIO E ON T.EMPRESA = E.CNPJ
WHERE
    T.EVENTO = 88 AND
    T.CARGO = 'Guilherme Sales'

-- LOCAIS DISPONÍVEIS PARA UMA DETERMINADA DATA E HORÁRIO
SELECT 
    *
FROM LOCAL L
WHERE 
	L.ID NOT IN (
		SELECT 
			E.LOCAL
		FROM EVENTO E
		WHERE 
			E.DATA = '2010-03-14' AND
			E.HORA_INICIO <= '07:35:34'/*INFORMAR A HORA FIM DO EVENTO QUE SE PRETENDE FAZER*/)
			
-- DATAS E HORÁRIOS INDISPONÍVEIS PARA UM DETERMINADO LOCAL
SELECT
	E.DATA,
	E.HORA_INICIO,
	E.HORA_FIM
FROM EVENTO E
WHERE
	E.LOCAL = 88 AND
	E.DATA >= '2010-03-10' AND -- DATA_INICIO
	E.DATA <= '2010-03-20' -- DATA_FIM

-- QUANTIDADE DE EVENTOS POR CIDADE EM UM PERÍODO DE TEMPO
SELECT 
	L.CIDADE,
	COUNT(E.ID) AS QTD
FROM EVENTO E
INNER JOIN LOCAL L ON E.LOCAL = L.ID
WHERE
	E.DATA >= '2000-01-01' AND
	E.DATA <= '2020-01-01'
GROUP BY
	L.CIDADE
	
-- Insumos / brinquedos / presentes mais consumidos em eventos
SELECT *
FROM
 (SELECT
  V.BRINQUEDO,
  COUNT(DISTINCT(V.FORMATURA)) AS QTD
 FROM
  VENDA_BRINQUEDO_FORMATURA V
 GROUP BY
  V.BRINQUEDO) G
WHERE
 G.QTD IN (SELECT
      MAX(QUERY.QTD)
     FROM (SELECT COUNT(DISTINCT(V.FORMATURA)) AS QTD
     FROM VENDA_BRINQUEDO_FORMATURA V
     GROUP BY V.BRINQUEDO) QUERY);
     

SELECT *
FROM
 (SELECT
  V.PRESENTE,
  COUNT(DISTINCT(V.CASAMENTO)) AS QTD
 FROM
  VENDA_PRESENTE_CASAMENTO V
 GROUP BY
  V.PRESENTE) G
WHERE
 G.QTD IN (SELECT
      MAX(QUERY.QTD)
     FROM (SELECT COUNT(DISTINCT(V.CASAMENTO)) AS QTD
     FROM VENDA_PRESENTE_CASAMENTO V
     GROUP BY V.PRESENTE) QUERY);
     
     
SELECT *
FROM
 (SELECT
  V.INSUMO,
  COUNT(DISTINCT(V.EVENTO)) AS QTD
 FROM
  VENDA_INSUMO_EVENTO V
 GROUP BY
  V.INSUMO) G
WHERE
 G.QTD IN (SELECT
      MAX(QUERY.QTD)
     FROM (SELECT COUNT(DISTINCT(V.EVENTO)) AS QTD
     FROM VENDA_INSUMO_EVENTO V
     GROUP BY V.INSUMO) QUERY);
     
     
-- Empresas fornecedoras de um determinado insumo, presente ou brinquedo
SELECT
 EMPRESA
FROM
 VENDA_INSUMO
WHERE
 INSUMO LIKE 'Cauê Alves'; --VARIÁVEL AQUI
 

SELECT
 EMPRESA
FROM
 VENDA_PRESENTE
WHERE
 PRESENTE LIKE 'Agatha Sales';--VARIÁVEL AQUI


SELECT
 EMPRESA
FROM
 VENDA_BRINQUEDO
WHERE
 BRINQUEDO LIKE 'Yuri Barros'; --VARIÁVEL AQUI	
	
